-- Log Analysis Reports Table
-- Stores results from the backend log analyzer agent
-- Part of the "Terminology Brain" for AI Search Assistant self-improvement

CREATE TABLE IF NOT EXISTS log_analysis_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Analysis metadata
  analysis_date DATE NOT NULL,
  logs_analyzed INT NOT NULL DEFAULT 0,
  time_range_start TIMESTAMPTZ,
  time_range_end TIMESTAMPTZ,

  -- Key metrics
  avg_recommendations_count DECIMAL(5,2) DEFAULT 0,
  zero_result_queries INT DEFAULT 0,
  low_confidence_queries INT DEFAULT 0,
  state_context_usage_count INT DEFAULT 0,
  competitor_query_count INT DEFAULT 0,

  -- AI-generated insights (the "brain" output)
  summary TEXT,
  issues_identified JSONB DEFAULT '[]',
  suggested_mappings JSONB DEFAULT '[]',
  pattern_insights JSONB DEFAULT '[]',

  -- Action items for improvement
  terminology_suggestions JSONB DEFAULT '[]',
  context_gaps JSONB DEFAULT '[]',
  state_context_usage JSONB DEFAULT '{}',

  -- Execution metadata
  execution_time_ms INT,
  model_used VARCHAR(50),
  error_message TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_log_analysis_date
  ON log_analysis_reports(analysis_date DESC);

CREATE INDEX IF NOT EXISTS idx_log_analysis_created
  ON log_analysis_reports(created_at DESC);

-- Index for finding reports with unresolved issues
CREATE INDEX IF NOT EXISTS idx_log_analysis_issues
  ON log_analysis_reports USING GIN (issues_identified)
  WHERE jsonb_array_length(issues_identified) > 0;

-- RLS Policies
ALTER TABLE log_analysis_reports ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read reports (for admin dashboard)
CREATE POLICY "Allow public read of log analysis reports"
  ON log_analysis_reports FOR SELECT
  USING (true);

-- Allow authenticated users to insert (for the analyzer script)
CREATE POLICY "Allow authenticated insert of log analysis reports"
  ON log_analysis_reports FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Comment on table
COMMENT ON TABLE log_analysis_reports IS 'Stores AI analysis of prompt logs to identify search quality issues and suggest improvements. Generated by the backend log_analyzer.py script.';
